version: "3.9"

services:
  web:
    build: .
    command: uvicorn myapp.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/myapp  # Adjust the path to match the WORKDIR
    ports:
      - "8000:8000"
    depends_on:
      - postgres-database
    environment:
      - DATABASE_URL=postgresql://user:password@postgres-db:5432/dbname?sslmode=disable

  postgres-database:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
      POSTGRES_HOST: postgres-db
      DATABASE_URL: postgresql://user:password@postgres-db:5432/dbname?sslmode=disable
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
